package by.htp.main.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, 
	GO_TO_REGISTRATION_PAGE, 
	GO_TO_NEWS_LIST, 
	GO_TO_VIEW_NEWS, 
	DO_LOG_IN, DO_LOG_OUT, 
	DO_REGISTRATION,
	
	ADD_NEWS,	
	EDIT_NEWS,
	COMPLETELY_DELETE_NEWS,
	DELETE_NEWS,
	GO_TO_DO_ACTION,
	CHANGE_LANGUAGE,
}
